### ISSUE TITLE
Distinct User-Agent header

### ISSUE THREAD

**Issue by cpu** [jannfis/acme-distributed#2]
Hi @jannfis,

Thanks for writing an ACME client :+1: 

A cursory scan makes me think your project might not be sending a distinct User-Agent header. This is super helpful for ACME server operators, and a MUST [in the draft RFC](https://tools.ietf.org/html/draft-ietf-acme-acme-16#section-6.1): 

>   ACME clients MUST send a User-Agent header field, in accordance with [RFC7231].  This header field SHOULD include the name and version of the ACME software in addition to the name and version of the underlying HTTP client software.

Would you be willing to add such a header? Thank you!

**Comment by jannfis** [comment]
Hi @cpu,

acme-distributed uses the acme-client library (https://github.com/unixcharles/acme-client) for requests to ACME APIs. This library sets User-Agent header with all of it requests but unfortunately, the library's API has no means to set a unique UA header from the client application.

Of course, there are ways in Ruby to override internals of libraries that a program uses. But those I'd consider truly bad hacks. So, if I'm interpreting the text from the RFC correctly, acme-distributed fulfills the hard requirement (i.e. MUST), because the underlying library does that already. As for good behaviour (i.e. SHOULD), I can implement this as a feature in acme-client library and submit a pull-request to its developers and maybe they'll accept it.

What do you think?

**Comment by cpu** [comment]
@jannfis I missed that you were using Unixcharles' acme-client. Sorry about that! That's what I get for quickly skimming code in an unfamiliar language :-)

I agree that you're meeting the requirement and I don't think its worth overriding the acme-client UA.

Thanks!
